FROM ghcr.io/iisas/domino-base-piece:latest
# Install specific requirements to run ShellExecute Piece
RUN apt-get update
RUN apt install net-tools
# RUN apt install iputils-ping

# Need to copy pieces source code
COPY config.toml pieces_repository/
COPY pieces pieces_repository/pieces
COPY .domino pieces_repository/.domino

# Install specific dependencies in domino_env virtual environment
# RUN pip install --no-cache-dir numpy==1.23.5 plotly==5.18.0
